class MaintenanceRequest {
  final int id;
  final String title;
  final String? assetName;
  final String? categoryName;
  final String? locationName;
  final String? assetCode;
  final String? responsiblePersonName;
  final String? email;
  final String? description;
  final String type; // preventive/corrective/other
  final String state; // draft, in_progress, done, etc.
  final DateTime? scheduledDate;
  final DateTime? scheduledEndDate;
  final String? priority;
  final String? userName;
  final String? teamName;
  final bool autoGenerated;
  final String? assetRecurrencePattern;
  final int? assetRecurrenceInterval;
  final DateTime? assetRecurrenceStartDate;
  final DateTime? assetRecurrenceEndDate;
  final DateTime? assetNextMaintenanceDate;

  MaintenanceRequest({
    required this.id,
    required this.title,
    required this.type,
    required this.state,
    this.assetName,
    this.categoryName,
    this.locationName,
    this.assetCode,
    this.responsiblePersonName,
    this.email,
    this.description,
    this.scheduledDate,
    this.scheduledEndDate,
    this.priority,
    this.userName,
    this.teamName,
    this.autoGenerated = false,
    this.assetRecurrencePattern,
    this.assetRecurrenceInterval,
    this.assetRecurrenceStartDate,
    this.assetRecurrenceEndDate,
    this.assetNextMaintenanceDate,
  });

  factory MaintenanceRequest.fromJson(Map<String, dynamic> json) {
    String? m2oName(dynamic v) {
      if (v is List && v.length >= 2) return (v[1] ?? '').toString();
      if (v is String) return v;
      return null;
    }
    DateTime? parseDate(dynamic v) {
      if (v == null) return null;
      try { return DateTime.parse(v.toString()); } catch (_) { return null; }
    }

    return MaintenanceRequest(
      id: json['id'] is String ? int.tryParse(json['id']) ?? 0 : (json['id'] ?? 0),
      title: (json['maintenance_request_title'] ?? json['name'] ?? '').toString(),
      assetName: m2oName(json['asset_id']),
      categoryName: m2oName(json['category_id']),
      locationName: m2oName(json['location_asset_id']),
      assetCode: json['asset_code']?.toString(),
      responsiblePersonName: m2oName(json['responsible_person_id']),
      email: json['email']?.toString(),
      description: json['description']?.toString(),
      type: (json['maintenance_type'] ?? 'preventive').toString(),
      state: (json['state'] ?? 'draft').toString(),
      scheduledDate: parseDate(json['scheduled_date']),
      scheduledEndDate: parseDate(json['scheduled_end_date']),
      priority: json['priority']?.toString(),
      userName: m2oName(json['user_id']),
      teamName: m2oName(json['team_id']),
      autoGenerated: (json['auto_generated'] ?? false) == true,
      assetRecurrencePattern: json['asset_recurrence_pattern']?.toString(),
      assetRecurrenceInterval: json['asset_recurrence_interval'] is num
          ? (json['asset_recurrence_interval'] as num).toInt()
          : int.tryParse(json['asset_recurrence_interval']?.toString() ?? ''),
      assetRecurrenceStartDate: parseDate(json['asset_recurrence_start_date']),
      assetRecurrenceEndDate: parseDate(json['asset_recurrence_end_date']),
      assetNextMaintenanceDate: parseDate(json['asset_next_maintenance_date']),
    );
  }
}
