// maintenance_page.dart
import 'package:flutter/material.dart';
import 'dart:async';
import '../../models/maintenance_request.dart';
import '../../services/api_service.dart';
import '../../services/auth_service.dart';
import '../maintenance_detail_page.dart';
import '../maintenance_create_page.dart';

class MaintenancePage extends StatefulWidget {
  final int? assetId;
  final bool autoGeneratedOnly;
  final bool showTitle;

  const MaintenancePage({super.key, this.assetId, this.autoGeneratedOnly = false, this.showTitle = false});

  @override
  State<MaintenancePage> createState() => _MaintenancePageState();
}

class _MaintenancePageState extends State<MaintenancePage> {
  final TextEditingController _search = TextEditingController();
  Timer? _debounce;
  String _query = '';
  bool _loading = false;
  String? _error;
  List<MaintenanceRequest> _items = [];
  bool _grid = true;
  bool _canManageMaintenance = false;
  bool _filterSheetOpen = false;
  String? _filterAssetName;
  String? _filterCategory;
  String? _filterLocation;
  String? _filterSerial;
  String? _filterResponsible;
  String? _filterStatus;
  String? _filterPattern;
  String? _filterStartDate;
  String? _filterInterval;
  String? _filterEndDate;
  List<String> _assetNameOptions = [];
  List<String> _categoryOptions = [];
  List<String> _locationOptions = [];
  List<String> _serialOptions = [];
  List<String> _responsibleOptions = [];
  List<String> _statusOptions = [];
  List<String> _patternOptions = [];
  List<String> _startDateOptions = [];
  List<String> _intervalOptions = [];
  List<String> _endDateOptions = [];

  @override
  void initState() {
    super.initState();
    _loadPermissions();
    _load();
  }

  @override
  void dispose() {
    _debounce?.cancel();
    _search.dispose();
    super.dispose();
  }

  Future<void> _load() async {
    setState(() { _loading = true; _error = null; });
    try {
      final res = await ApiService.fetchMaintenanceRequests(
        query: _query,
        assetId: widget.assetId,
        autoGeneratedOnly: widget.autoGeneratedOnly,
      );
      if (!mounted) return;
      setState(() {
        _items = res;
        _assetNameOptions = _buildOptions(res.map((m) => m.assetName));
        _categoryOptions = _buildOptions(res.map((m) => m.categoryName));
        _locationOptions = _buildOptions(res.map((m) => m.locationName));
        _serialOptions = _buildOptions(res.map((m) => m.assetCode));
        _responsibleOptions = _buildOptions(res.map((m) => m.responsiblePersonName));
        _statusOptions = _buildOptions(res.map((m) => m.state));
        _patternOptions = _buildOptions(res.map((m) => m.assetRecurrencePattern));
        _startDateOptions = _buildOptions(res.map((m) => _formatDate(m.assetRecurrenceStartDate)));
        _intervalOptions = _buildOptions(res.map((m) => m.assetRecurrenceInterval?.toString()));
        _endDateOptions = _buildOptions(res.map((m) => _formatDate(m.assetRecurrenceEndDate)));
      });
    } catch (e) {
      if (!mounted) return;
      setState(() { _error = e.toString(); });
    } finally {
      if (mounted) setState(() { _loading = false; });
    }
  }

  Future<void> _loadPermissions() async {
    // 1) Gunakan role yang tersimpan di lokal terlebih dahulu
    try {
      final cachedRole = await AuthService.getUserRole();
      if (cachedRole != null && cachedRole.isNotEmpty && mounted) {
        final canManage = cachedRole == 'Manager' || cachedRole == 'Team';
        setState(() {
          _canManageMaintenance = canManage;
        });
      }
    } catch (_) {}

    // 2) Refresh dari API, sekaligus memastikan role terbaru
    try {
      final info = await ApiService.fetchCurrentUserInfo();
      if (!mounted) return;
      final role = (info['role'] ?? '').toString();
      final canManage = role == 'Manager' || role == 'Team';
      setState(() {
        _canManageMaintenance = canManage;
      });
    } catch (_) {
      // Biarkan pakai cached role jika ada
    }
  }

  Widget _buildPriorityStars(String? priority) {
    int p = int.tryParse(priority ?? '') ?? 0;
    if (p < 0) p = 0;
    if (p > 3) p = 3;
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: List.generate(3, (index) {
        final selected = index < p;
        return Icon(
          Icons.star,
          size: 14,
          color: selected ? Colors.amber : Colors.grey.shade300,
        );
      }),
    );
  }

  Color _stateColor(String s) {
    switch (s.toLowerCase()) {
      case 'done':
        return const Color(0xFF16A34A);
      case 'repaired':
        return const Color(0xFFDC2626);
      case 'in_progress':
        return const Color(0xFFF59E0B);
      case 'cancelled':
      case 'cancel':
        return const Color(0xFFEF4444);
      case 'draft':
        return const Color(0xFF6B7280);
      default:
        return const Color(0xFF6B7280);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: widget.showTitle
          ? AppBar(
              title: const Text('Maintenance Requests'),
            )
          : null,
      body: RefreshIndicator(
        onRefresh: _load,
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Expanded(
                    child: SizedBox(
                      height: 46,
                      child: TextField(
                        controller: _search,
                        onTap: () async {
                          FocusScope.of(context).unfocus();
                          if (!_filterSheetOpen) {
                            await _openFilterDialog();
                          }
                        },
                        onChanged: (v) {
                          setState(() => _query = v);
                          _debounce?.cancel();
                          _debounce = Timer(const Duration(milliseconds: 300), _load);
                        },
                        decoration: InputDecoration(
                          hintText: 'Cari maintenance...',
                          prefixIcon: const Icon(Icons.search),
                          filled: true,
                          fillColor: Colors.white,
                          contentPadding: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: const BorderSide(color: Color(0xFFE5E7EB)),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: const BorderSide(color: Color(0xFF1E3A8A)),
                          ),
                          suffixIcon: Container(
                            margin: const EdgeInsets.symmetric(vertical: 8),
                            decoration: const BoxDecoration(
                              border: Border(
                                left: BorderSide(color: Color(0xFFE5E7EB)),
                              ),
                            ),
                            child: AnimatedRotation(
                              turns: _filterSheetOpen ? 0.5 : 0.0,
                              duration: const Duration(milliseconds: 200),
                              child: IconButton(
                                tooltip: 'Filter',
                                icon: const Icon(Icons.filter_list),
                                onPressed: _openFilterDialog,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  IconButton(
                    tooltip: _grid ? 'Tampilkan list' : 'Tampilkan grid',
                    onPressed: () => setState(() => _grid = !_grid),
                    icon: Icon(_grid ? Icons.view_list_rounded : Icons.grid_view_rounded),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              Expanded(
                child: Builder(
                  builder: (context) {
                    if (_loading) {
                      return const Center(child: CircularProgressIndicator());
                    }
                    if (_error != null) {
                      return Center(child: Text(_error!));
                    }
                    if (_items.isEmpty) {
                      return const Center(child: Text('Tidak ada data'));
                    }

                    final filteredItems = _applyFilters();
                    if (filteredItems.isEmpty) {
                      return const Center(child: Text('Tidak ada data'));
                    }

                    return _grid
                        ? GridView.builder(
                          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                            crossAxisCount: 2,
                            crossAxisSpacing: 12,
                            mainAxisSpacing: 12,
                            // dibuat sedikit lebih tinggi supaya konten (judul, asset, priority, tanggal) tidak overflow
                            childAspectRatio: 0.8,
                          ),
                          itemCount: filteredItems.length,
                          itemBuilder: (context, index) {
                            final m = filteredItems[index];
                                    return InkWell(
                                      onTap: () {
                                        Navigator.of(context).push(
                                          MaterialPageRoute(
                                            builder: (_) => MaintenanceDetailPage(request: m),
                                          ),
                                        );
                                      },
                                      child: Card(
                                        elevation: 2,
                                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                        child: Padding(
                                          padding: const EdgeInsets.all(12.0),
                                          child: Column(
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Row(
                                                children: [
                                                  Container(
                                                    padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 8),
                                                    decoration: BoxDecoration(
                                                      color: _stateColor(m.state).withOpacity(0.15),
                                                      borderRadius: BorderRadius.circular(999),
                                                    ),
                                                    child: Text(
                                                      m.state.toUpperCase(),
                                                      style: TextStyle(
                                                        color: _stateColor(m.state),
                                                        fontSize: 12,
                                                        fontWeight: FontWeight.bold,
                                                      ),
                                                    ),
                                                  ),
                                                  const Spacer(),
                                                  const Icon(Icons.build_rounded, color: Colors.grey),
                                                ],
                                              ),
                                              const SizedBox(height: 12),
                                              Text(
                                                m.title,
                                                maxLines: 2,
                                                overflow: TextOverflow.ellipsis,
                                                style: const TextStyle(fontWeight: FontWeight.bold),
                                              ),
                                              Text(
                                                m.assetName ?? '-',
                                                style: const TextStyle(color: Colors.grey)),
                                              const SizedBox(height: 4),
                                              _buildPriorityStars(m.priority),
                                              const Spacer(),
                                              if (m.scheduledDate != null)
                                                Text(
                                                  '${m.scheduledDate!.toLocal()}'.split(' ').first,
                                                  style: const TextStyle(color: Colors.grey),
                                                ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    );
                                  },
                                )
                                : ListView.separated(
                                    itemCount: filteredItems.length,
                                    separatorBuilder: (_, __) => const Divider(height: 1),
                                    itemBuilder: (context, index) {
                                      final m = filteredItems[index];
                                      return ListTile(
                                        title: Column(
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          mainAxisSize: MainAxisSize.min,
                                          children: [
                                            Text(
                                              m.title,
                                              maxLines: 1,
                                              overflow: TextOverflow.ellipsis,
                                            ),
                                            const SizedBox(height: 4),
                                            _buildPriorityStars(m.priority),
                                          ],
                                        ),
                                        subtitle: Text([
                                          if (m.assetName != null) m.assetName!,
                                          if (m.scheduledDate != null)
                                            '${m.scheduledDate!.toLocal()}'.split(' ').first,
                                        ].join(' · ')),
                                        trailing: Container(
                                          padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 8),
                                          decoration: BoxDecoration(
                                            color: _stateColor(m.state).withOpacity(0.15),
                                            borderRadius: BorderRadius.circular(999),
                                          ),
                                          child: Text(
                                            m.state.toUpperCase(),
                                            style: TextStyle(
                                              color: _stateColor(m.state),
                                              fontSize: 12,
                                              fontWeight: FontWeight.bold,
                                            ),
                                          ),
                                        ),
                                        onTap: () {
                                          Navigator.of(context).push(
                                            MaterialPageRoute(
                                              builder: (_) => MaintenanceDetailPage(request: m),
                                            ),
                                          );
                                        },
                                      );
                                    },
                                  );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: _canManageMaintenance
          ? FloatingActionButton(
              onPressed: () async {
                final created = await Navigator.of(context).push<bool>(
                  MaterialPageRoute(
                    builder: (_) => MaintenanceCreatePage(
                      assetId: widget.assetId,
                      assetName: null,
                    ),
                  ),
                );
                if (created == true) {
                  await _load();
                }
              },
              backgroundColor: Theme.of(context).primaryColor,
              child: const Icon(Icons.add, color: Colors.white),
            )
          : null,
    );
  }

  List<MaintenanceRequest> _applyFilters() {
    final q = _query.trim().toLowerCase();
    return _items.where((m) {
      final matchesQuickSearch = q.isEmpty ||
          m.title.toLowerCase().contains(q) ||
          (m.assetName ?? '').toLowerCase().contains(q) ||
          (m.assetCode ?? '').toLowerCase().contains(q) ||
          (m.categoryName ?? '').toLowerCase().contains(q) ||
          (m.locationName ?? '').toLowerCase().contains(q);

      final matchesAssetName = _matchesFilter(m.assetName, _filterAssetName);
      final matchesCategory = _matchesFilter(m.categoryName, _filterCategory);
      final matchesLocation = _matchesFilter(m.locationName, _filterLocation);
      final matchesSerial = _matchesFilter(m.assetCode, _filterSerial);
      final matchesResponsible = _matchesFilter(m.responsiblePersonName, _filterResponsible);
      final matchesStatus = _matchesFilter(m.state, _filterStatus);

      final pattern = m.assetRecurrencePattern;
      final startDate = _formatDate(m.assetRecurrenceStartDate);
      final interval = m.assetRecurrenceInterval?.toString();
      final endDate = _formatDate(m.assetRecurrenceEndDate);

      final matchesPattern = _matchesFilter(pattern, _filterPattern);
      final matchesStartDate = _matchesFilter(startDate, _filterStartDate);
      final matchesInterval = _matchesFilter(interval, _filterInterval);
      final matchesEndDate = _matchesFilter(endDate, _filterEndDate);

      return matchesQuickSearch &&
          matchesAssetName &&
          matchesCategory &&
          matchesLocation &&
          matchesSerial &&
          matchesResponsible &&
          matchesStatus &&
          matchesPattern &&
          matchesStartDate &&
          matchesInterval &&
          matchesEndDate;
    }).toList();
  }

  bool _matchesFilter(String? source, String? filter) {
    final trimmed = filter?.trim();
    if (trimmed == null || trimmed.isEmpty) return true;
    return (source ?? '').toLowerCase().contains(trimmed.toLowerCase());
  }

  Future<void> _openFilterDialog() async {
    setState(() {
      _filterSheetOpen = true;
    });

    final names = _assetNameOptions;
    final categories = _categoryOptions;
    final locations = _locationOptions;
    final serials = _serialOptions;
    final responsibles = _responsibleOptions;
    final statuses = _statusOptions;
    final patterns = _patternOptions;
    final startDates = _startDateOptions;
    final intervals = _intervalOptions;
    final endDates = _endDateOptions;

    String? tempAssetName = _filterAssetName;
    String? tempCategory = _filterCategory;
    String? tempLocation = _filterLocation;
    String? tempSerial = _filterSerial;
    String? tempResponsible = _filterResponsible;
    String? tempStatus = _filterStatus;
    String? tempPattern = _filterPattern;
    String? tempStartDate = _filterStartDate;
    String? tempInterval = _filterInterval;
    String? tempEndDate = _filterEndDate;

    final result = await showModalBottomSheet<bool>(
      context: context,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
      ),
      builder: (ctx) {
        final bottomInset = MediaQuery.of(ctx).viewInsets.bottom;
        return StatefulBuilder(
          builder: (ctx, modalSetState) {
            return Padding(
              padding: EdgeInsets.only(bottom: bottomInset),
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(16),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Row(
                          children: const [
                            Icon(Icons.filter_list, color: Color(0xFF6C63FF)),
                            SizedBox(width: 8),
                            Text(
                              'Filters',
                              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                            ),
                          ],
                        ),
                        const Spacer(),
                        IconButton(
                          onPressed: () => Navigator.of(ctx).pop(false),
                          icon: const Icon(Icons.close),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    ExpansionTile(
                      tilePadding: EdgeInsets.zero,
                      initiallyExpanded: false,
                      title: const Text(
                        'Asset Information',
                        style: TextStyle(fontWeight: FontWeight.w600),
                      ),
                      children: [
                        _buildFilterDropdown(
                          label: 'Asset name',
                          value: tempAssetName,
                          options: names,
                          onChanged: (v) => modalSetState(() => tempAssetName = v),
                        ),
                        _buildFilterDropdown(
                          label: 'Asset Category',
                          value: tempCategory,
                          options: categories,
                          onChanged: (v) => modalSetState(() => tempCategory = v),
                        ),
                        _buildFilterDropdown(
                          label: 'Location Assets',
                          value: tempLocation,
                          options: locations,
                          onChanged: (v) => modalSetState(() => tempLocation = v),
                        ),
                        _buildFilterDropdown(
                          label: 'Serial number',
                          value: tempSerial,
                          options: serials,
                          onChanged: (v) => modalSetState(() => tempSerial = v),
                        ),
                        _buildFilterDropdown(
                          label: 'Responsible',
                          value: tempResponsible,
                          options: responsibles,
                          onChanged: (v) => modalSetState(() => tempResponsible = v),
                        ),
                        _buildFilterDropdown(
                          label: 'Status',
                          value: tempStatus,
                          options: statuses,
                          onChanged: (v) => modalSetState(() => tempStatus = v),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    ExpansionTile(
                      tilePadding: EdgeInsets.zero,
                      initiallyExpanded: false,
                      title: const Text(
                        'Recurrence Settings',
                        style: TextStyle(fontWeight: FontWeight.w600),
                      ),
                      children: [
                        _buildFilterDropdown(
                          label: 'Pattern',
                          value: tempPattern,
                          options: patterns,
                          onChanged: (v) => modalSetState(() => tempPattern = v),
                        ),
                        _buildFilterDropdown(
                          label: 'Start Date',
                          value: tempStartDate,
                          options: startDates,
                          onChanged: (v) => modalSetState(() => tempStartDate = v),
                        ),
                        _buildFilterDropdown(
                          label: 'Interval (days)',
                          value: tempInterval,
                          options: intervals,
                          onChanged: (v) => modalSetState(() => tempInterval = v),
                        ),
                        _buildFilterDropdown(
                          label: 'End Date',
                          value: tempEndDate,
                          options: endDates,
                          onChanged: (v) => modalSetState(() => tempEndDate = v),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        TextButton(
                          onPressed: () {
                            modalSetState(() {
                              tempAssetName = null;
                              tempCategory = null;
                              tempLocation = null;
                              tempSerial = null;
                              tempResponsible = null;
                              tempStatus = null;
                              tempPattern = null;
                              tempStartDate = null;
                              tempInterval = null;
                              tempEndDate = null;
                            });
                            Navigator.of(ctx).pop(true);
                          },
                          child: const Text('Reset'),
                        ),
                        const Spacer(),
                        FilledButton(
                          onPressed: () {
                            Navigator.of(ctx).pop(true);
                          },
                          child: const Text('Apply Filter'),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                  ],
                ),
              ),
            );
          },
        );
      },
    );

    if (!mounted) return;
    setState(() {
      _filterSheetOpen = false;
    });
    if (result == true) {
      setState(() {
        _filterAssetName = tempAssetName;
        _filterCategory = tempCategory;
        _filterLocation = tempLocation;
        _filterSerial = tempSerial;
        _filterResponsible = tempResponsible;
        _filterStatus = tempStatus;
        _filterPattern = tempPattern;
        _filterStartDate = tempStartDate;
        _filterInterval = tempInterval;
        _filterEndDate = tempEndDate;
      });
    }
  }

  Widget _buildFilterDropdown({
    required String label,
    required List<String> options,
    required String? value,
    required ValueChanged<String?> onChanged,
  }) {
    final items = [''].followedBy(options).toList();
    return Padding(
      padding: const EdgeInsets.only(bottom: 12, left: 8, right: 8),
      child: InputDecorator(
        decoration: InputDecoration(
          labelText: label,
          border: const OutlineInputBorder(),
        ),
        child: DropdownButtonHideUnderline(
          child: DropdownButton<String>(
            isExpanded: true,
            value: value ?? '',
            items: items
                .map(
                  (e) => DropdownMenuItem<String>(
                    value: e,
                    child: Text(e.isEmpty ? 'All' : e),
                  ),
                )
                .toList(),
            onChanged: (selected) {
              if (selected == null || selected.isEmpty) {
                onChanged(null);
              } else {
                onChanged(selected);
              }
            },
          ),
        ),
      ),
    );
  }

  List<String> _buildOptions(Iterable<String?> values) {
    final set = <String>{};
    for (final raw in values) {
      final trimmed = raw?.trim();
      if (trimmed != null && trimmed.isNotEmpty) {
        set.add(trimmed);
      }
    }
    final list = set.toList()
      ..sort((a, b) => a.toLowerCase().compareTo(b.toLowerCase()));
    return list;
  }

  String _formatDate(DateTime? d) {
    if (d == null) return '';
    return '${d.toLocal()}'.split(' ').first;
  }
}